services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: codeskins-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: codeskins
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - codeskins-network

  # Backend API (Fastify)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codeskins-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3001
      HOST: 0.0.0.0
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/codeskins?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - codeskins-network

volumes:
  mongodb_data:

networks:
  codeskins-network:
    driver: bridge 